generator:
  numar_linii: 5000
  lungime_id: 5
  cale_iesire_csv: "cars.csv"

migrare:
  cale_intrare_csv: "cars.csv"
  cale_baza_date: "cars.db"
  nume_tabel: "masini"

server:
  port: ":9977"
  api_endpoint: "/"

atribute:
  marci:
    - "Dacia"
    - "Aro"
    - "DAC"
    - "Roman"
    - "Rocar"
    - "Oltcit"
  culori:
    - "Alb"
    - "Negru"
    - "Rosu"
    - "Albastru"
    - "Verde"
    - "Galben"
    - "Gri"
  locatie_blocuri:
    - "Zona A1"
    - "Bloc Nord"
    - "Terminal Sud"
    - "A5"
  greutate_interval:
    min: 600
    max: 3500
  marime_interval:
    min: 3
    max: 15